Fixing stopprocs
Basically reverted a change in commit: 578db32c71a3e4379bd2b30f54b9e69855f338d5

Error:  Could not kill Fixpack, PID 25384 25385 25386 .
        In order to install/upgrade to specified target: /opt/IBM/HTTPServer85,
        all related processes need to be stopped.
        Output of 'kill 25384 25385 25386 ':